_target_: src.modules.sae.SAEModule

variant: batchtopk
input_size: ${model.input_size}
hidden_size: ${model.hidden_size}
learning_rate: 1e-4
top_k: 64
top_k_aux: 512
aux_penalty: 0.03125
n_batches_to_dead: 5
